// Mocks generated by Mockito 5.0.2 from annotations
// in gql_app/test/data/datasources/country/country_remote_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:gql_app/data/core/api_client/jobs_api_client.dart' as _i3;
import 'package:graphql/src/core/query_options.dart' as _i5;
import 'package:graphql/src/core/query_result.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeQueryResult extends _i1.Fake implements _i2.QueryResult {}

/// A class which mocks [JobsApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobsApiClient extends _i1.Mock implements _i3.JobsApiClient {
  MockJobsApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.QueryResult> query(_i5.QueryOptions? options) =>
      (super.noSuchMethod(Invocation.method(#query, [options]),
              returnValue: Future.value(_FakeQueryResult()))
          as _i4.Future<_i2.QueryResult>);
}
