// Mocks generated by Mockito 5.0.2 from annotations
// in gql_app/test/domain/repositories/country/country_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:gql_app/data/core/api_client/jobs_api_client.dart' as _i2;
import 'package:gql_app/data/datasources/country/country_remote_data_source.dart'
    as _i3;
import 'package:gql_app/data/models/country_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeJobsApiClient extends _i1.Fake implements _i2.JobsApiClient {}

/// A class which mocks [CountryRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCountryRemoteDataSource extends _i1.Mock
    implements _i3.CountryRemoteDataSource {
  MockCountryRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.JobsApiClient get client =>
      (super.noSuchMethod(Invocation.getter(#client),
          returnValue: _FakeJobsApiClient()) as _i2.JobsApiClient);
  @override
  _i4.Future<List<_i5.CountryModel>> getCountries() =>
      (super.noSuchMethod(Invocation.method(#getCountries, []),
              returnValue: Future.value(<_i5.CountryModel>[]))
          as _i4.Future<List<_i5.CountryModel>>);
}
